input
js-tasks-ru/htmlcss-20220519_kuzzzzzina pull request #17
Opened 2022-06-13 19:29 UTC by Kuzzzzzina

2022-06-13 19:30 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-06-13 19:38 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-14 20:20 UTC, GSemikozov requested changes

2022-06-14 20:20 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.form {
это отдельный блок, его описывать в блоке .input нельзя. Если хочется сохранить в примере эти стили - выносим в тег style

2022-06-16 14:53 UTC, GSemikozov approved these changes

2022-06-16 14:53 UTC, merged