Accordion
js-tasks-ru/htmlcss-20220519_kuzzzzzina pull request #5
Opened 2022-05-26 07:21 UTC by Kuzzzzzina

2022-05-26 07:22 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-26 14:47 UTC, GSemikozov requested changes

2022-05-26 14:47 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    border: 2px solid var(--grey-3);
1px

2022-05-26 14:47 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +        <details class="accordion__item" open>
элементы не могут существовать вне своего блока)
поэтому все айтемы надо завернуть в див с классом accordion

2022-05-30 10:30 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-30 10:36 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-05 11:04 UTC, GSemikozov approved these changes

2022-06-05 11:04 UTC, merged